steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - builds
      - submit
      - --config=eng/cloudbuild.yaml
    id: Deploy
    entrypoint: gcloud
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _PLATFORM: managed
  _SERVICE_NAME: dkpweb
  REPO_NAME: dinnerkillpoints
  _TRIGGER_ID: unspecified
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - dkpweb
