<?xml version="1.0" encoding="utf-8"?><Database Name="DKP" Class="DkpDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=DKP;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DKPConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BillSplit" Member="BillSplits">
    <Type Name="BillSplit">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="BillSplit_Transaction" Member="Transactions" ThisKey="ID" OtherKey="BillID" Type="Transaction" />
    </Type>
  </Table>
  <Table Name="dbo.[Transaction]" Member="Transactions">
    <Type Name="Transaction">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DebtorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreditorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BillID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BillSplit_Transaction" Member="BillSplit" ThisKey="BillID" OtherKey="ID" Type="BillSplit" IsForeignKey="true" />
      <Association Name="Person_Transaction" Member="Creditor" ThisKey="CreditorID" OtherKey="ID" Type="Person" IsForeignKey="true" />
      <Association Name="Person_Transaction1" Member="Debtor" ThisKey="DebtorID" OtherKey="ID" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Person" Member="People">
    <Type Name="Person">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Person_Transaction" Member="Credits" ThisKey="ID" OtherKey="CreditorID" Type="Transaction" />
      <Association Name="Person_Transaction1" Member="Debts" ThisKey="ID" OtherKey="DebtorID" Type="Transaction" />
    </Type>
  </Table>
</Database>