apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/operation-id: 4e0fc5a4-8680-48be-a484-714ac6a72204
    serving.knative.dev/creator: austinwise@gmail.com
    serving.knative.dev/lastModifier: austinwise@gmail.com
  creationTimestamp: '2023-07-09T19:53:12.930459Z'
  generation: 58
  labels:
    cloud.googleapis.com/location: us-central1
    commit-sha: 7f75bdacdff102e8b7a6fc3f4c8a1dbfaf9fa88d
    gcb-build-id: e2cdb1e1-7cc1-4db8-ae30-cb7b4e477ac6
    gcb-trigger-id: 382f9163-3e5c-406d-8694-38650839fccd
    gcb-trigger-region: global
    managed-by: gcp-cloud-build-deploy-cloud-run
  name: dkpweb
  namespace: '216611213396'
  resourceVersion: AAYGsxw+QYw
  selfLink: /apis/serving.knative.dev/v1/namespaces/216611213396/services/dkpweb
  uid: 83053708-04d8-4a54-981f-77c2ed887ef2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 448.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: avknqyqzod
        commit-sha: 7f75bdacdff102e8b7a6fc3f4c8a1dbfaf9fa88d
        gcb-build-id: e2cdb1e1-7cc1-4db8-ae30-cb7b4e477ac6
        gcb-trigger-id: 382f9163-3e5c-406d-8694-38650839fccd
        gcb-trigger-region: global
        managed-by: gcp-cloud-build-deploy-cloud-run
        run.googleapis.com/startupProbeType: Custom
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: DataProtection__Bucket
          value: dkp-settings
        - name: DataProtection__ObjectName
          value: DataProtectionKeys.xml
        - name: GcpProjectId
          value: '216611213396'
        - name: ConnectionStrings__Postgres
          value: host=127.0.0.1; database=dkp; username=dkp-service-account@dinnerkillpoints.iam;
            password=test;
        image: us-central1-docker.pkg.dev/dinnerkillpoints/cloud-run-source-deploy/dinnerkillpoints/dkpweb:7f75bdacdff102e8b7a6fc3f4c8a1dbfaf9fa88d
        name: dkp
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 2
          timeoutSeconds: 1
      - args:
        - --structured-logs
        - --auto-iam-authn
        - --health-check
        - --http-address=0.0.0.0
        - austinsql:us-central1:austinsql
        image: us.gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.7.0
        name: sql
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
        startupProbe:
          failureThreshold: 5
          httpGet:
            path: /startup
            port: 9090
          periodSeconds: 2
          timeoutSeconds: 1
      serviceAccountName: dkp-service-account@dinnerkillpoints.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://dkpweb-cvempurorq-uc.a.run.app
  conditions:
  - lastTransitionTime: '2023-10-02T03:10:02.913288Z'
    status: 'True'
    type: Ready
  - lastTransitionTime: '2023-10-02T03:02:27.404485Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2023-10-02T03:10:03.018636Z'
    status: 'True'
    type: RoutesReady
  latestCreatedRevisionName: dkpweb-00055-6sq
  latestReadyRevisionName: dkpweb-00055-6sq
  observedGeneration: 58
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: dkpweb-00055-6sq
  url: https://dkpweb-cvempurorq-uc.a.run.app
