apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/operation-id: 624be2b4-df44-4bcf-b079-8c30fcfd7957
    serving.knative.dev/creator: austinwise@gmail.com
    serving.knative.dev/lastModifier: austinwise@gmail.com
  creationTimestamp: '2023-07-09T19:53:12.930459Z'
  generation: 61
  labels:
    cloud.googleapis.com/location: us-central1
    commit-sha: 38e51ad9d5067b0d9f0e054399ad0fe6db8a4af2
    gcb-build-id: b68e5a45-e4b5-4f39-93f0-263b280f5dd4
    gcb-trigger-id: 382f9163-3e5c-406d-8694-38650839fccd
    gcb-trigger-region: global
    managed-by: gcp-cloud-build-deploy-cloud-run
  name: dkpweb
  namespace: '216611213396'
  resourceVersion: AAYGtc+bEj8
  selfLink: /apis/serving.knative.dev/v1/namespaces/216611213396/services/dkpweb
  uid: 83053708-04d8-4a54-981f-77c2ed887ef2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: 56db45c4-5670-4ae6-8182-5bd444c027ca
        commit-sha: 38e51ad9d5067b0d9f0e054399ad0fe6db8a4af2
        gcb-build-id: b68e5a45-e4b5-4f39-93f0-263b280f5dd4
        gcb-trigger-id: 382f9163-3e5c-406d-8694-38650839fccd
        gcb-trigger-region: global
        managed-by: gcp-cloud-build-deploy-cloud-run
        run.googleapis.com/startupProbeType: Custom
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: DataProtection__Bucket
          value: dkp-settings
        - name: DataProtection__ObjectName
          value: DataProtectionKeys.xml
        - name: GcpProjectId
          value: '216611213396'
        - name: ConnectionStrings__Postgres
          value: host=127.0.0.1; database=dkp; username=dkp-service-account@dinnerkillpoints.iam;
            password=test;
        image: us-central1-docker.pkg.dev/dinnerkillpoints/cloud-run-source-deploy/dinnerkillpoints/dkpweb:38e51ad9d5067b0d9f0e054399ad0fe6db8a4af2
        name: dkp
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 2
          timeoutSeconds: 1
      - args:
        - --structured-logs
        - --auto-iam-authn
        - --health-check
        - --http-address=0.0.0.0
        - austinsql:us-central1:austinsql
        image: us.gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.7.0
        name: sql
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
        startupProbe:
          failureThreshold: 5
          httpGet:
            path: /startup
            port: 9090
          periodSeconds: 2
          timeoutSeconds: 1
      serviceAccountName: dkp-service-account@dinnerkillpoints.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://dkpweb-cvempurorq-uc.a.run.app
  conditions:
  - lastTransitionTime: '2023-10-02T06:23:22.075072Z'
    status: 'True'
    type: Ready
  - lastTransitionTime: '2023-10-02T06:23:03.638628Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2023-10-02T06:23:22.157631Z'
    status: 'True'
    type: RoutesReady
  latestCreatedRevisionName: dkpweb-00058-528
  latestReadyRevisionName: dkpweb-00058-528
  observedGeneration: 61
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: dkpweb-00058-528
  url: https://dkpweb-cvempurorq-uc.a.run.app
